services:
  broker1:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}${PLATFORM}
    hostname: broker1
    container_name: broker1
    ports:
      - "9092:9092"
    environment:
      # https://kafka.apache.org/documentation/#brokerconfigs_controller.quorum.voters
      CLUSTER_ID: ${CLUSTER_ID}
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker1:9092'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker1:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:29092'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_NODE_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
    volumes:
      - type: volume
        source: kafka1_data
        target: /var/lib/kafka

  akhq:
    image: tchiotludo/akhq:latest
    environment:
      JAVA_OPTS: -Duser.timezone=Europe/Amsterdam
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local:
              properties:
                bootstrap.servers: "broker1:9092"
    ports:
      - "8405:8080"

  kafka-setup:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}${PLATFORM}
    container_name: kafka-setup
    depends_on:
      - "broker1"
    command: /bin/bash -c '/usr/bin/kafka-topics --bootstrap-server broker1:9092 --create --if-not-exists --topic test --partitions 3 --replication-factor 1'

  producer:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}${PLATFORM}
    container_name: producer
    depends_on:
      - "broker1"
      - "kafka-setup"
    command: /bin/bash -c 'for nr in {1..1000000}; do echo "$(date +%s) "#"$$nr"; sleep .5; done | /usr/bin/kafka-console-producer --request-required-acks all --broker-list broker1:9092 --topic test'

  consumer:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}${PLATFORM}
    container_name: consumer
    depends_on:
      - "broker1"
      - kafka-setup
    command: /bin/sh -c '/usr/bin/kafka-console-consumer --bootstrap-server broker1:9092 --topic test --from-beginning'


volumes:
  kafka1_data:
